In [71]:
import numpy as np
def pos_conv(a,b,m):
    n = len(a)
    c = np.zeros(n)
    for i in range(n):
        first = [a[j]*b[i-j] for j in range(0,i+1)]
        second = [a[j]*b[n+i-j] for j in range(i+1,n)]
        c[i] = (sum(first) + sum(second)) % m
    return c
        
def neg_conv(a,b,m):
    n = len(a)
    c = np.zeros(n)
    for i in range(n):
        first = [a[j]*b[i-j] for j in range(0,i+1)]
        second = [a[j]*b[n+i-j] for j in range(i+1,n)]
        c[i] = (sum(first) - sum(second)) % m
    return c

# Задание 6

In [76]:
neg_conv([0,1,2,4],[2,2,4,3],17)

array([15., 14., 11., 16.])

# Задание 5

In [131]:
n = 5 # вектора длины n
fourier = np.zeros((n,n))

In [132]:
for i in range(n):
    for j in range(n):
        fourier[i,j] = 2**(i*j) % 31

In [133]:
inv_fourier = np.zeros((n,n))

In [134]:
for i in range(n):
    for j in range(n):
        inv_fourier[i,j] = 25*(16**(i*j)) % 31

In [135]:
inv_fourier @ fourier % 31

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [137]:
inv_fourier @ np.asarray([4,3,3,2,1]) % 31

array([15., 11., 14.,  9., 17.])

# Задание 1

In [157]:
def binary_power(x,y):
    result = 1
    while y > 0:
        if y % 2 == 1:
            result *= x
        x*=x
        y //= 2
    return result
# поскольку каждый шаг цикла мы уменьшаем степень как минимум вдвое за постоянное число операций,
# временная сложность - O(log_2(y))